# Generated by Django 4.2.6 on 2023-10-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名字')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('age', models.CharField(max_length=256, verbose_name='年龄')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
