# Generated by Django 4.2.6 on 2023-10-15 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='is_delete',
        ),
    ]
