# Generated by Django 4.2.6 on 2023-10-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_userinfo_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='is_delete',
            field=models.BooleanField(default=True, verbose_name='启用状态'),
        ),
    ]
