# Generated by Django 4.2.6 on 2023-10-15 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_userinfo_is_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='is_delete',
            new_name='is_activate',
        ),
    ]
