# Generated by Django 4.2.6 on 2023-10-18 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraddress',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='customerbalancelog',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='customerlevelinfo',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='customerlogin',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='customerloginlog',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='customerpointlog',
            name='is_activate',
        ),
    ]
