# Generated by Django 4.2.6 on 2023-10-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerbalancelog',
            options={'verbose_name': '用户余额变动表', 'verbose_name_plural': '用户余额变动表'},
        ),
        migrations.AlterModelOptions(
            name='customerinfo',
            options={'verbose_name': '用户信息表', 'verbose_name_plural': '用户信息表'},
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='register_time',
        ),
        migrations.RemoveField(
            model_name='customerpointlog',
            name='password',
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='gender',
            field=models.IntegerField(choices=[('0', 'man'), ('1', 'woman'), ('2', 'null')], default=2, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='last_login_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后一次登录时间'),
        ),
        migrations.AddField(
            model_name='customerlogin',
            name='customer_email',
            field=models.CharField(default=1, max_length=50, verbose_name='用户邮箱'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='user_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='账户余额'),
        ),
    ]
