# Generated by Django 4.2.6 on 2023-10-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='is_activate',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='启用状态'),
        ),
        migrations.AddField(
            model_name='customerbalancelog',
            name='is_activate',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='启用状态'),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='is_activate',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='启用状态'),
        ),
        migrations.AddField(
            model_name='customerlevelinfo',
            name='is_activate',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='启用状态'),
        ),
        migrations.AddField(
            model_name='customerlogin',
            name='is_activate',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='启用状态'),
        ),
        migrations.AddField(
            model_name='customerloginlog',
            name='is_activate',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='启用状态'),
        ),
        migrations.AddField(
            model_name='customerpointlog',
            name='is_activate',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='启用状态'),
        ),
    ]
