# Generated by Django 4.2.6 on 2023-10-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customerbalancelog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinfo',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='identity_card_no',
        ),
        migrations.RemoveField(
            model_name='customerlogin',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='customerlogin',
            name='is_active',
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='customer_name',
            field=models.CharField(default=1, max_length=50, verbose_name='用户真实姓名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='customer_email',
            field=models.CharField(default=1, max_length=50, verbose_name='用户邮箱'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='login_name',
            field=models.CharField(default=1, max_length=50, verbose_name='用户登录名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='password',
            field=models.CharField(default=1, max_length=128, verbose_name='用户登录密码'),
            preserve_default=False,
        ),
    ]
