# Generated by Django 4.2.6 on 2023-10-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customeraddress_is_delete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='is_delete',
            field=models.BooleanField(default=True, verbose_name='启用状态'),
        ),
        migrations.AlterField(
            model_name='customerbalancelog',
            name='is_delete',
            field=models.BooleanField(default=True, verbose_name='启用状态'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='is_delete',
            field=models.BooleanField(default=True, verbose_name='启用状态'),
        ),
        migrations.AlterField(
            model_name='customerlevelinfo',
            name='is_delete',
            field=models.BooleanField(default=True, verbose_name='启用状态'),
        ),
        migrations.AlterField(
            model_name='customerlogin',
            name='is_delete',
            field=models.BooleanField(default=True, verbose_name='启用状态'),
        ),
        migrations.AlterField(
            model_name='customerloginlog',
            name='is_delete',
            field=models.BooleanField(default=True, verbose_name='启用状态'),
        ),
        migrations.AlterField(
            model_name='customerpointlog',
            name='is_delete',
            field=models.BooleanField(default=True, verbose_name='启用状态'),
        ),
    ]
