# Generated by Django 4.2.6 on 2023-10-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_customerinfo_customer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraddress',
            name='password',
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='mobile_phone',
            field=models.CharField(default=1, max_length=50, verbose_name='收件人手机号码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='customer_name',
            field=models.CharField(max_length=50, verbose_name='收件人姓名'),
        ),
    ]
