# Generated by Django 4.2.6 on 2023-10-15 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customeraddress_is_delete_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeraddress',
            old_name='is_delete',
            new_name='is_activate',
        ),
        migrations.RenameField(
            model_name='customerbalancelog',
            old_name='is_delete',
            new_name='is_activate',
        ),
        migrations.RenameField(
            model_name='customerinfo',
            old_name='is_delete',
            new_name='is_activate',
        ),
        migrations.RenameField(
            model_name='customerlevelinfo',
            old_name='is_delete',
            new_name='is_activate',
        ),
        migrations.RenameField(
            model_name='customerlogin',
            old_name='is_delete',
            new_name='is_activate',
        ),
        migrations.RenameField(
            model_name='customerloginlog',
            old_name='is_delete',
            new_name='is_activate',
        ),
        migrations.RenameField(
            model_name='customerpointlog',
            old_name='is_delete',
            new_name='is_activate',
        ),
    ]
