# Generated by Django 4.2.6 on 2023-11-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_customeraddress_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='customer_email',
            field=models.CharField(max_length=50, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='login_name',
            field=models.CharField(max_length=50, verbose_name='User name'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='mobile_phone',
            field=models.CharField(max_length=50, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Password'),
        ),
    ]
