# Generated by Django 4.2.6 on 2023-10-16 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_is_delete_customeraddress_is_activate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraddress',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='customerbalancelog',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='customerbalancelog',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='customerlevelinfo',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='customerlevelinfo',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='customerlogin',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='customerlogin',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='customerlogin',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='customerloginlog',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='customerloginlog',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='customerpointlog',
            name='is_activate',
        ),
    ]
