# Generated by Django 4.2.6 on 2023-11-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customerinfo_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='birthday',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='会员生日'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='user_money',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='账户余额'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='user_point',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='用户积分'),
        ),
    ]
