# Generated by Django 4.2.6 on 2023-11-02 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customerinfo_birthday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinfo',
            name='customer_id',
        ),
    ]
