# Generated by Django 4.2.6 on 2023-11-03 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_shopcomment_customer_id'),
        ('user', '0007_remove_customerinfo_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerinfo',
            old_name='customer_email',
            new_name='login_email',
        ),
        migrations.RenameField(
            model_name='customerinfo',
            old_name='login_name',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='customerbalancelog',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='customerloginlog',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='customerpointlog',
            name='customer_id',
        ),
        migrations.DeleteModel(
            name='CustomerLogin',
        ),
    ]
