# Generated by Django 4.2.6 on 2023-11-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_customer_email_customerinfo_login_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_activate', models.BooleanField(blank=True, default=True, null=True, verbose_name='启用状态')),
                ('login_email', models.CharField(max_length=50, verbose_name='Email address')),
                ('user_name', models.CharField(max_length=50, verbose_name='User name')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('mobile_phone', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('last_login_time', models.DateTimeField(blank=True, null=True, verbose_name='最后一次登录时间')),
            ],
            options={
                'verbose_name': '用户登陆表',
                'verbose_name_plural': '用户登陆表',
                'db_table': 'user_customer_login',
            },
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='login_email',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='mobile_phone',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='customerlevelinfo',
            name='password',
        ),
    ]
