# Generated by Django 4.2.6 on 2023-11-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_customerlogin_remove_customerinfo_login_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlogin',
            name='login_email',
            field=models.EmailField(max_length=50, verbose_name='Email address'),
        ),
    ]
