# Generated by Django 4.2.6 on 2023-11-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_ordercart_customer_id_and_more'),
        ('user', '0010_alter_customerlogin_login_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerInfo',
        ),
        migrations.AddField(
            model_name='customerlogin',
            name='birthday',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='会员生日'),
        ),
        migrations.AddField(
            model_name='customerlogin',
            name='gender',
            field=models.IntegerField(choices=[('0', 'man'), ('1', 'woman'), ('2', 'null')], default=2, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='customerlogin',
            name='user_money',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='账户余额'),
        ),
        migrations.AddField(
            model_name='customerlogin',
            name='user_point',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='用户积分'),
        ),
    ]
