# Generated by Django 4.2.6 on 2023-11-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_delete_customerinfo_customerlogin_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlogin',
            name='gender',
            field=models.IntegerField(choices=[('0', 'man'), ('1', 'woman'), ('2', 'null')], verbose_name='性别'),
        ),
    ]
