# Generated by Django 4.2.6 on 2023-11-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_customerlogin_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlogin',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='会员生日'),
        ),
        migrations.AlterField(
            model_name='customerlogin',
            name='gender',
            field=models.IntegerField(choices=[('1', 'man'), ('2', 'woman'), ('3', 'null')], default=3, verbose_name='性别'),
        ),
    ]
