# Generated by Django 4.2.6 on 2023-11-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_customerlogin_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbalancelog',
            name='source_sn',
            field=models.SmallIntegerField(choices=[(1, 'order'), (2, 'rejected')], verbose_name='相关单据'),
        ),
        migrations.AlterField(
            model_name='customerloginlog',
            name='source_sn',
            field=models.SmallIntegerField(choices=[('1', 'succeed'), ('2', 'def')], verbose_name='相关单据'),
        ),
    ]
