# Generated by Django 4.2.6 on 2023-11-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_customerlogin_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerlogin',
            name='avatar',
            field=models.ImageField(default='avatar/avatar.png', upload_to='avatar/', verbose_name='头像'),
        ),
    ]
