# Generated by Django 4.2.5 on 2023-10-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jf_goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150, verbose_name='Product Title')),
                ('listing', models.CharField(max_length=150, verbose_name='listing')),
            ],
        ),
    ]
