# Generated by Django 4.2.6 on 2023-10-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_jf_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='是否可用')),
                ('materia', models.CharField(max_length=150, verbose_name='产品')),
                ('self_control', models.CharField(max_length=150, verbose_name='自制')),
                ('subcontract', models.CharField(max_length=150, verbose_name='委外加工')),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='是否可用')),
                ('product', models.CharField(max_length=150, verbose_name='产品')),
                ('office_supplies', models.CharField(max_length=150, verbose_name='办公用品')),
                ('production_supplies', models.CharField(max_length=150, verbose_name='生产用品')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='是否可用')),
                ('spu_id', models.CharField(max_length=150, verbose_name='SPUID')),
                ('item_name', models.CharField(max_length=150, verbose_name='产品名称')),
                ('detail_description', models.TextField(blank=True, null=True, verbose_name='产品详细描述')),
                ('price', models.CharField(max_length=150, verbose_name='产品价格')),
                ('unit', models.CharField(max_length=150, verbose_name='单位')),
                ('stock', models.CharField(max_length=150, verbose_name='库存')),
                ('sales_volume', models.CharField(max_length=150, verbose_name='销量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=10)),
                ('conversion_factor', models.FloatField()),
            ],
        ),
    ]
