# Generated by Django 4.2.6 on 2023-10-17 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('item', '0001_initial'),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(editable=False, max_length=20, unique=True, verbose_name='订单编号')),
                ('shipping_user', models.CharField(editable=False, max_length=20, unique=True, verbose_name='订单编号')),
                ('country', models.CharField(default='', max_length=50, verbose_name='国家')),
                ('province', models.CharField(default='', max_length=50, verbose_name='州')),
                ('city', models.CharField(default='', max_length=50, verbose_name='城市')),
                ('district', models.CharField(default='', max_length=50, verbose_name='区')),
                ('address', models.CharField(default='', max_length=200, verbose_name='详细地址')),
                ('order_money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单金额')),
                ('district_money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='优惠金额')),
                ('shipping_money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='运费金额')),
                ('payment_money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='支付金额')),
                ('shipping_comp_name', models.CharField(default='', max_length=200, verbose_name='快递公司名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('shipping_time', models.DateTimeField(auto_now_add=True, verbose_name='发货时间')),
                ('payment_time', models.DateTimeField(auto_now_add=True, verbose_name='发货时间')),
                ('receive_time', models.DateTimeField(auto_now_add=True, verbose_name='收货时间')),
                ('order_point', models.CharField(default='', max_length=200, verbose_name='订单积分')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_master', to='user.customerinfo', verbose_name='下单人ID')),
            ],
            options={
                'verbose_name': '订单主表',
                'verbose_name_plural': '订单主表',
                'db_table': 'order_master',
            },
        ),
        migrations.CreateModel(
            name='ShopBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('logo', models.ImageField(upload_to='', verbose_name='Logo图片')),
                ('first_letter', models.CharField(max_length=1, verbose_name='品牌首字母')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
                'db_table': 'shop_brand',
            },
        ),
        migrations.CreateModel(
            name='ShopChannelGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='频道组名')),
            ],
            options={
                'verbose_name': '商品频道组',
                'verbose_name_plural': '商品频道组',
                'db_table': 'shop_channel_group',
            },
        ),
        migrations.CreateModel(
            name='ShopSPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=10, verbose_name='物料型号:(JF-D-***)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('power', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='功率')),
                ('warranty', models.IntegerField(default=0, verbose_name='保修期')),
                ('apply', models.CharField(max_length=8, verbose_name='应用范围')),
                ('color', models.CharField(max_length=64, verbose_name='灯光颜色')),
                ('transport_package', models.CharField(max_length=64, verbose_name='包装方式')),
                ('listing', models.CharField(max_length=250, verbose_name='详细介绍')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('sales', models.IntegerField(default=0, verbose_name='销量')),
                ('likes', models.IntegerField(default=0, verbose_name='收藏')),
                ('default_image_url', models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='product/', verbose_name='默认图片')),
            ],
            options={
                'verbose_name': '商品SPU',
                'verbose_name_plural': '商品SPU',
                'db_table': 'shop_spu',
            },
        ),
        migrations.CreateModel(
            name='ShopComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='激活状态')),
                ('title', models.CharField(max_length=100, verbose_name='评论标题')),
                ('content', models.CharField(max_length=300, verbose_name='评论内容')),
                ('audit_status', models.BooleanField(default=False, verbose_name='审核状态')),
                ('audit_time', models.DateTimeField(auto_now_add=True, verbose_name='评论创建时间')),
                ('audit_update_time', models.DateTimeField(auto_now=True, verbose_name='评论修改时间')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_comment', to='user.customerlogin', verbose_name='用户登陆ID')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_comment', to='item.itemsku', verbose_name='商品ID')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_comment', to='shop.ordermaster', verbose_name='订单iD')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_comment', to='system.team')),
            ],
            options={
                'verbose_name': '商品评论表',
                'verbose_name_plural': '商品评论表',
                'db_table': 'shop_comment',
            },
        ),
        migrations.CreateModel(
            name='ShopChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50, verbose_name='频道页面链接')),
                ('sequence', models.IntegerField(verbose_name='组内顺序')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_channel', to='item.itemcategory', verbose_name='顶级商品类别')),
            ],
            options={
                'verbose_name': '商品频道',
                'verbose_name_plural': '商品频道',
                'db_table': 'shop_channel',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(verbose_name='订单表ID')),
                ('product_cnt', models.IntegerField(default=0, verbose_name='购买商品数量')),
                ('weight', models.CharField(default='', max_length=200, verbose_name='商品重量')),
                ('fee_money', models.CharField(default='', max_length=200, verbose_name='优惠分摊金额')),
                ('w_id', models.CharField(default='', max_length=200, verbose_name='仓库ID')),
                ('modified_time', models.CharField(default='', max_length=200, verbose_name='订单积分')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='item.itemsku', verbose_name='下单人ID')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='user.customerinfo', verbose_name='下单人ID')),
                ('product_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='shop.shopspu', verbose_name='商品价格')),
            ],
            options={
                'verbose_name': '订单详情表',
                'verbose_name_plural': '订单详情表',
                'db_table': 'order_detail',
            },
        ),
        migrations.CreateModel(
            name='OrderCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(verbose_name='订单表ID')),
                ('product_amount', models.IntegerField(verbose_name='加入购物车的数量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='加入购物车时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_cart', to='user.customerinfo', verbose_name='用户ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_cart', to='item.itemsku', verbose_name='物料编码')),
                ('product_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_cart', to='shop.shopspu', verbose_name='商品价格')),
            ],
            options={
                'verbose_name': '购物车表',
                'verbose_name_plural': '购物车表',
                'db_table': 'order_cart',
            },
        ),
    ]
