# Generated by Django 4.2.6 on 2023-10-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsku',
            name='item_sku',
            field=models.CharField(max_length=16, verbose_name='物料编码(F2.2.09.30.00000)'),
        ),
    ]
