# Generated by Django 4.2.6 on 2023-10-18 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopspu',
            name='price',
        ),
    ]
