# Generated by Django 4.2.6 on 2023-10-15 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercart',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='ordermaster',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='shopbrand',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='shopchannel',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='shopchannelgroup',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='shopcomment',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='shopimageinfo',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='shopspu',
            name='is_delete',
        ),
    ]
