# Generated by Django 4.2.6 on 2023-10-18 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_itemsku_sales'),
        ('user', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopsku',
            options={'verbose_name': '商品SKU', 'verbose_name_plural': '商品SKU'},
        ),
        migrations.RemoveField(
            model_name='shopcomment',
            name='audit_status',
        ),
        migrations.RemoveField(
            model_name='shopcomment',
            name='is_active',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order_sn',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orderdetail_ordermaster', to='shop.ordermaster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopsku',
            name='item_sku',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shopspu_itemsku', to='item.itemsku'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderdetail_itemsku', to='item.itemsku', verbose_name='下单人ID'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderdetail_customerinfo', to='user.customerinfo', verbose_name='下单人ID'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderdetail_shopsku', to='shop.shopsku', verbose_name='商品价格'),
        ),
        migrations.AlterField(
            model_name='shopbrand',
            name='logo',
            field=models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='LOGO/', verbose_name='LOGO图片'),
        ),
        migrations.AlterField(
            model_name='shopsku',
            name='image_son1',
            field=models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='product/{}', verbose_name='产品辅图1'),
        ),
        migrations.AlterField(
            model_name='shopsku',
            name='image_son2',
            field=models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='product/', verbose_name='产品辅图2'),
        ),
        migrations.AlterField(
            model_name='shopsku',
            name='image_son3',
            field=models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='product/', verbose_name='产品辅图3'),
        ),
        migrations.AlterField(
            model_name='shopsku',
            name='image_son4',
            field=models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='product/', verbose_name='产品辅图4'),
        ),
        migrations.AlterField(
            model_name='shopsku',
            name='image_son5',
            field=models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='product/', verbose_name='产品辅图5'),
        ),
        migrations.AlterField(
            model_name='shopsku',
            name='image_son6',
            field=models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='product/', verbose_name='产品辅图6'),
        ),
        migrations.AlterField(
            model_name='shopsku',
            name='image_son7',
            field=models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='product/', verbose_name='产品辅图7'),
        ),
        migrations.AlterField(
            model_name='shopsku',
            name='image_son8',
            field=models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='product/', verbose_name='产品辅图8'),
        ),
        migrations.AlterField(
            model_name='shopsku',
            name='image_son9',
            field=models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='product/', verbose_name='产品辅图9'),
        ),
    ]
