# Generated by Django 4.2.6 on 2023-10-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsku',
            name='lens',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='透镜类型'),
        ),
    ]
