# Generated by Django 4.2.6 on 2023-10-18 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_itemsku_unite'),
        ('shop', '0002_alter_shopsku_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcomment',
            name='fa_star',
            field=models.IntegerField(default=0, verbose_name='评论星星'),
        ),
        migrations.AddField(
            model_name='shopspu',
            name='fa_star',
            field=models.IntegerField(default=0, verbose_name='评论星星'),
        ),
        migrations.AlterField(
            model_name='shopsku',
            name='item_sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopspu_itemsku', to='item.itemsku'),
        ),
    ]
