# Generated by Django 4.2.6 on 2023-10-31 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_shopsku_lens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsku',
            name='a_led_num',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=16, null=True, verbose_name='A板灯珠数量'),
        ),
        migrations.AlterField(
            model_name='shopsku',
            name='a_pcb_num',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=16, null=True, verbose_name='A板数量'),
        ),
        migrations.AlterField(
            model_name='shopsku',
            name='b_led_num',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=16, null=True, verbose_name='B板灯珠数量'),
        ),
        migrations.AlterField(
            model_name='shopsku',
            name='c_led_num',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=16, null=True, verbose_name='C板灯珠数量'),
        ),
        migrations.AlterField(
            model_name='shopsku',
            name='d_led_num',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=16, null=True, verbose_name='D板灯珠数量'),
        ),
        migrations.AlterField(
            model_name='shopsku',
            name='e_led_num',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=16, null=True, verbose_name='E板灯珠数量'),
        ),
        migrations.AlterField(
            model_name='shopsku',
            name='f_led_num',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=16, null=True, verbose_name='F板灯珠数量'),
        ),
    ]
