# Generated by Django 4.2.6 on 2023-10-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_shopsku_goods_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopbrand',
            name='logo',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='logo/', verbose_name='LOGO图片'),
        ),
    ]
