# Generated by Django 4.2.6 on 2023-10-19 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_shopsku_item_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopspu',
            name='fa_star',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='评论星星'),
        ),
    ]
