# Generated by Django 4.2.6 on 2023-10-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_shopsku_a_pcb_w_remove_shopsku_b_pcb_w_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsku',
            name='pcb_w',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='PCB宽度'),
        ),
    ]
