# Generated by Django 4.2.6 on 2023-10-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_ordercart_is_delete_orderdetail_is_delete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercart',
            name='is_delete',
            field=models.BooleanField(default=True, verbose_name='启用状态'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='is_delete',
            field=models.BooleanField(default=True, verbose_name='启用状态'),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='is_delete',
            field=models.BooleanField(default=True, verbose_name='启用状态'),
        ),
        migrations.AlterField(
            model_name='shopbrand',
            name='is_delete',
            field=models.BooleanField(default=True, verbose_name='启用状态'),
        ),
        migrations.AlterField(
            model_name='shopchannel',
            name='is_delete',
            field=models.BooleanField(default=True, verbose_name='启用状态'),
        ),
        migrations.AlterField(
            model_name='shopchannelgroup',
            name='is_delete',
            field=models.BooleanField(default=True, verbose_name='启用状态'),
        ),
        migrations.AlterField(
            model_name='shopcomment',
            name='is_delete',
            field=models.BooleanField(default=True, verbose_name='启用状态'),
        ),
        migrations.AlterField(
            model_name='shopimageinfo',
            name='is_delete',
            field=models.BooleanField(default=True, verbose_name='启用状态'),
        ),
        migrations.AlterField(
            model_name='shopspu',
            name='is_delete',
            field=models.BooleanField(default=True, verbose_name='启用状态'),
        ),
    ]
