# Generated by Django 4.2.6 on 2023-10-23 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shopbrand_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopsku',
            name='image10',
        ),
        migrations.RemoveField(
            model_name='shopsku',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='shopsku',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='shopsku',
            name='image9',
        ),
    ]
