# Generated by Django 4.2.6 on 2023-10-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shopspu_fa_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopspu',
            name='customer',
            field=models.IntegerField(default=0, verbose_name='评论'),
        ),
    ]
