# Generated by Django 4.2.6 on 2023-10-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shopsku_pcb_w'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsku',
            name='a_pcb_l',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='A板PCB长度'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopsku',
            name='a_pcb_num',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2, verbose_name='一套几条A板'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopsku',
            name='b_cnt',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='连接器2'),
        ),
        migrations.AlterField(
            model_name='shopsku',
            name='c_cnt',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='连接器3'),
        ),
        migrations.AlterField(
            model_name='shopsku',
            name='d_cnt',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='连接器4'),
        ),
        migrations.AlterField(
            model_name='shopsku',
            name='image1',
            field=models.ImageField(default=1, upload_to='product/', verbose_name='主图'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopsku',
            name='o_code1',
            field=models.CharField(default=1, max_length=200, verbose_name='原厂代码1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopsku',
            name='pcb_material',
            field=models.CharField(default=1, max_length=8, verbose_name='PCB类型'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopsku',
            name='pcb_t',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, verbose_name='PCB厚度'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopsku',
            name='pcb_w',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='PCB宽度'),
            preserve_default=False,
        ),
    ]
