# Generated by Django 4.2.6 on 2023-10-18 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shopcomment_fa_star_shopspu_fa_star_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercart',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='ordermaster',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='shopbrand',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='shopchannel',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='shopchannelgroup',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='shopcomment',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='shopsku',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='shopspu',
            name='is_activate',
        ),
    ]
