# Generated by Django 4.2.6 on 2023-11-03 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shopsku_a_led_num_alter_shopsku_a_pcb_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcomment',
            name='customer_id',
        ),
    ]
