# Generated by Django 4.2.6 on 2023-10-20 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_shopsku_a_pcb_l_alter_shopsku_a_pcb_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopsku',
            name='application',
        ),
    ]
