# Generated by Django 4.2.6 on 2023-10-19 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shopspu_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopspu',
            old_name='customer',
            new_name='comments',
        ),
    ]
