# Generated by Django 4.2.6 on 2023-10-23 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_shopsku_image10_remove_shopsku_image7_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopsku',
            name='brand',
        ),
    ]
