# Generated by Django 4.2.6 on 2023-11-03 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_customerlogin_login_email'),
        ('shop', '0004_remove_shopcomment_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercart',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_cart', to='user.customerlogin', verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderdetail_customerinfo', to='user.customerlogin', verbose_name='下单人ID'),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_master', to='user.customerlogin', verbose_name='下单人ID'),
        ),
    ]
