# Generated by Django 4.2.6 on 2023-11-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_ordercart_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercart',
            name='product_price',
        ),
        migrations.AddField(
            model_name='shopbrand',
            name='slug',
            field=models.SlugField(default=1, max_length=55, verbose_name='品牌 Slug'),
            preserve_default=False,
        ),
    ]
