# Generated by Django 4.2.6 on 2023-10-20 08:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_shopsku_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopsku',
            name='pcb_material',
        ),
        migrations.AddField(
            model_name='shopsku',
            name='comments',
            field=models.IntegerField(default=0, verbose_name='评论'),
        ),
        migrations.AddField(
            model_name='shopsku',
            name='fa_star',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='评论星星'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopsku',
            name='likes_num',
            field=models.IntegerField(default=0, verbose_name='收藏'),
        ),
        migrations.AddField(
            model_name='shopsku',
            name='listing',
            field=models.TextField(default=1, verbose_name='listing'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordercart',
            name='product_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_cart', to='shop.shopsku', verbose_name='商品价格'),
        ),
        migrations.AlterField(
            model_name='shopsku',
            name='a_pcb_l',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='A板PCB长度'),
        ),
        migrations.AlterField(
            model_name='shopsku',
            name='goods_name',
            field=models.CharField(max_length=64, verbose_name='物料型号:(JF-D-***)'),
        ),
        migrations.AlterField(
            model_name='shopsku',
            name='pcb_t',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='PCB厚度'),
        ),
        migrations.AlterField(
            model_name='shopsku',
            name='pcb_w',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='PCB宽度'),
        ),
        migrations.DeleteModel(
            name='ShopSPU',
        ),
    ]
