# Generated by Django 4.2.6 on 2023-10-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_is_delete_ordercart_is_activate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermaster',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='shopimageinfo',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='shopspu',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='shopspu',
            name='is_launched',
        ),
        migrations.AddField(
            model_name='shopspu',
            name='goods',
            field=models.CharField(default=1, max_length=64, verbose_name='物料型号:JF-D-002'),
            preserve_default=False,
        ),
    ]
