# Generated by Django 4.2.6 on 2023-11-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_ordercart_product_price_shopbrand_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopbrand',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='品牌名称'),
        ),
    ]
