# Generated by Django 4.2.6 on 2023-10-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_delete_shopchannel_shopbrand_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercart',
            name='is_activate',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='启用状态'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='is_activate',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='启用状态'),
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='is_activate',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='启用状态'),
        ),
        migrations.AddField(
            model_name='shopbrand',
            name='is_activate',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='启用状态'),
        ),
        migrations.AddField(
            model_name='shopchannelgroup',
            name='is_activate',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='启用状态'),
        ),
        migrations.AddField(
            model_name='shopcomment',
            name='is_activate',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='启用状态'),
        ),
        migrations.AddField(
            model_name='shopsku',
            name='is_activate',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='启用状态'),
        ),
    ]
