# Generated by Django 4.2.6 on 2023-10-16 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_ordermaster_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopspu',
            name='category',
        ),
        migrations.RemoveField(
            model_name='shopspu',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='shopspu',
            name='name',
        ),
    ]
