# Generated by Django 4.2.6 on 2023-10-20 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_shopsku_pcb_material_shopsku_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsku',
            name='comment_num',
            field=models.IntegerField(default=0, verbose_name='评论数量'),
        ),
        migrations.AlterField(
            model_name='shopcomment',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_comment', to='shop.shopsku', verbose_name='商品ID'),
        ),
    ]
