# Generated by Django 4.2.6 on 2023-10-20 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_shopsku_comment_num_alter_shopcomment_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopsku',
            name='led_power',
        ),
    ]
