# Generated by Django 4.2.6 on 2023-10-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_shopspu_emitting_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopspu',
            name='apply',
            field=models.CharField(default=2, max_length=64, verbose_name='应用范围'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopspu',
            name='warranty',
            field=models.IntegerField(default=0, verbose_name='保修期'),
        ),
    ]
