# Generated by Django 4.2.6 on 2023-10-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_shopsku_led_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsku',
            name='led_power',
            field=models.CharField(choices=[('1', '1W'), ('2', '2W'), ('3', '3W')], default=2, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopsku',
            name='pcb_material',
            field=models.CharField(choices=[('1', 'FR4'), ('2', 'MCPCB (Aluminum) ')], default=2, max_length=2),
            preserve_default=False,
        ),
    ]
