# Generated by Django 4.2.6 on 2023-10-16 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_shopspu_apply_alter_shopspu_warranty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercart',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='ordermaster',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='ordermaster',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='shopbrand',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='shopbrand',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='shopbrand',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='shopchannel',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='shopchannel',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='shopchannel',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='shopchannelgroup',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='shopchannelgroup',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='shopchannelgroup',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='shopcomment',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='shopcomment',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='shopcomment',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='shopimageinfo',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='shopimageinfo',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='shopimageinfo',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='shopspu',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='shopspu',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='shopspu',
            name='update_time',
        ),
    ]
