# Generated by Django 4.2.6 on 2023-10-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_shopsku_led_power_shopsku_pcb_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsku',
            name='led_power',
            field=models.CharField(choices=[('1', '1W'), ('2', '2W'), ('3', '3W')], max_length=5),
        ),
        migrations.AlterField(
            model_name='shopsku',
            name='pcb_material',
            field=models.CharField(choices=[('1', 'FR4'), ('2', 'MCPCB (Aluminum) ')], max_length=5),
        ),
    ]
