# Generated by Django 4.2.6 on 2023-10-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_shopsku_led_power_alter_shopsku_pcb_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsku',
            name='led_power',
            field=models.CharField(choices=[('1', '1W'), ('2', '2W'), ('3', '3W')], max_length=2),
        ),
        migrations.AlterField(
            model_name='shopsku',
            name='pcb_material',
            field=models.CharField(choices=[('1', 'FR4'), ('2', 'MCPCB (Aluminum) ')], max_length=2),
        ),
    ]
