# Generated by Django 4.2.6 on 2023-10-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_ordercart_is_activate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopspu',
            name='apply',
            field=models.CharField(max_length=8, verbose_name='应用范围'),
        ),
        migrations.AlterField(
            model_name='shopspu',
            name='desc_detail',
            field=models.CharField(max_length=16, verbose_name='详细介绍'),
        ),
        migrations.AlterField(
            model_name='shopspu',
            name='goods',
            field=models.CharField(max_length=10, verbose_name='物料型号:JF-D-002'),
        ),
    ]
