# Generated by Django 4.2.6 on 2023-10-16 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_shopspu_apply_alter_shopspu_desc_detail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopspu',
            old_name='goods',
            new_name='goods_name',
        ),
    ]
