# Generated by Django 4.2.6 on 2023-10-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_rename_goods_shopspu_goods_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopspu',
            name='default_image_url',
            field=models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='product/', verbose_name='默认图片'),
        ),
        migrations.AlterField(
            model_name='shopspu',
            name='goods_name',
            field=models.CharField(max_length=10, verbose_name='物料型号:(JF-D-***)'),
        ),
    ]
