# Generated by Django 4.2.6 on 2023-10-21 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_shopchannelgroup_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopchannelgroup',
            options={'verbose_name': '商品频道组', 'verbose_name_plural': '商品频道组'},
        ),
        migrations.AlterModelTable(
            name='shopchannelgroup',
            table='shop_channel_group',
        ),
    ]
