# Generated by Django 4.2.6 on 2023-10-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_shopchannelgroup_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopsku',
            name='brand',
        ),
        migrations.AddField(
            model_name='shopsku',
            name='brand',
            field=models.ManyToManyField(related_name='spu_brand', to='shop.shopbrand'),
        ),
    ]
