# Generated by Django 4.2.6 on 2023-10-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_shopsku_brand_shopsku_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsku',
            name='brand',
            field=models.ManyToManyField(to='shop.shopbrand', verbose_name='品牌'),
        ),
    ]
