# Generated by Django 4.2.6 on 2023-10-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_shopsku_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSKUImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('image1', models.ImageField(upload_to='product/', verbose_name='主图')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='辅图')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='辅图')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='辅图')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='辅图')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='辅图')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='辅图')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='辅图')),
                ('image9', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='辅图')),
                ('image10', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='辅图')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
                'db_table': 'shop_sku_image',
            },
        ),
        migrations.RemoveField(
            model_name='shopsku',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='shopsku',
            name='image10',
        ),
        migrations.RemoveField(
            model_name='shopsku',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='shopsku',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='shopsku',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='shopsku',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='shopsku',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='shopsku',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='shopsku',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='shopsku',
            name='image9',
        ),
    ]
