# Generated by Django 4.2.6 on 2023-10-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_shopskuimage_remove_shopsku_image1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopSKUImage',
        ),
        migrations.AddField(
            model_name='shopsku',
            name='image1',
            field=models.ImageField(default=1, upload_to='product/', verbose_name='主图'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopsku',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='辅图'),
        ),
        migrations.AddField(
            model_name='shopsku',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='辅图'),
        ),
        migrations.AddField(
            model_name='shopsku',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='辅图'),
        ),
        migrations.AddField(
            model_name='shopsku',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='辅图'),
        ),
        migrations.AddField(
            model_name='shopsku',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='辅图'),
        ),
        migrations.AddField(
            model_name='shopsku',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='辅图'),
        ),
        migrations.AddField(
            model_name='shopsku',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='辅图'),
        ),
        migrations.AddField(
            model_name='shopsku',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='辅图'),
        ),
        migrations.AddField(
            model_name='shopsku',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='辅图'),
        ),
    ]
