# Generated by Django 4.2.6 on 2023-10-18 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(default='PCB属性', max_length=10, verbose_name='物料类属性')),
                ('name_id', models.CharField(default='1.5.03.01', max_length=9, verbose_name='四级物料代码')),
                ('remark', models.CharField(blank=True, default='关于啥啥啥的属性,和啥啥啥不一样', max_length=256, null=True, verbose_name='备注')),
                ('spec_0', models.CharField(blank=True, max_length=64, null=True, verbose_name='自定义属性0')),
                ('spec_1', models.CharField(blank=True, max_length=64, null=True, verbose_name='自定义属性1')),
                ('spec_2', models.CharField(blank=True, max_length=64, null=True, verbose_name='自定义属性2')),
                ('spec_3', models.CharField(blank=True, max_length=64, null=True, verbose_name='自定义属性3')),
                ('spec_4', models.CharField(blank=True, max_length=64, null=True, verbose_name='自定义属性4')),
                ('spec_5', models.CharField(blank=True, max_length=64, null=True, verbose_name='自定义属性5')),
                ('spec_6', models.CharField(blank=True, max_length=64, null=True, verbose_name='自定义属性6')),
                ('spec_7', models.CharField(blank=True, max_length=64, null=True, verbose_name='自定义属性7')),
                ('spec_8', models.CharField(blank=True, max_length=64, null=True, verbose_name='自定义属性8')),
                ('spec_9', models.CharField(blank=True, max_length=64, null=True, verbose_name='自定义属性9')),
            ],
            options={
                'verbose_name': '物料属性表',
                'verbose_name_plural': '物料属性表',
                'db_table': 'item_specification',
            },
        ),
        migrations.CreateModel(
            name='ItemUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '产品单位表',
                'verbose_name_plural': '产品单位表',
                'db_table': 'item_unit',
            },
        ),
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ship_name', models.CharField(max_length=50, verbose_name='物流公司名称')),
                ('link_man', models.CharField(max_length=256, verbose_name='物流公司联系人')),
                ('phone_number', models.CharField(max_length=50, verbose_name='物流公司联系人电话')),
                ('price', models.CharField(max_length=50, verbose_name='价格')),
            ],
            options={
                'verbose_name': '物流公司信息表',
                'verbose_name_plural': '物流公司信息表',
                'db_table': 'item_ShippingInfo',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('supplier_code', models.CharField(default='JF0000', max_length=10, verbose_name='供应商编码')),
                ('supplier_name', models.CharField(default='深圳市有限公司', max_length=50, verbose_name='供应商名称')),
                ('link_man', models.CharField(default='胡八一', max_length=256, verbose_name='联系人')),
                ('phone_number', models.CharField(default='13566200014', max_length=50, verbose_name='联系人电话')),
                ('bank_name', models.CharField(default='中国银行深圳分行', max_length=50, verbose_name='供应商开户银行名称')),
                ('bank_account', models.CharField(default='6226097558970588', max_length=50, verbose_name='银行账号')),
                ('address', models.CharField(default='广东省深圳市宝安区石岩街道65号', max_length=50, verbose_name='供应商地址')),
            ],
            options={
                'verbose_name': '供应商信息表',
                'verbose_name_plural': '供应商信息表',
                'db_table': 'item_supplier',
            },
        ),
        migrations.CreateModel(
            name='WarehouseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('warehouse_code', models.CharField(default='001', max_length=50, verbose_name='仓库编码')),
                ('warehouse_name', models.CharField(default='深圳仓库', max_length=50, verbose_name='仓库名称')),
                ('link_man', models.CharField(default='王八一', max_length=256, verbose_name='仓库联系人')),
                ('phone_number', models.CharField(default='15892564569', max_length=50, verbose_name='仓库联系人电话')),
                ('province', models.CharField(default='广东省', max_length=50, verbose_name='省')),
                ('city', models.CharField(default='深圳市', max_length=50, verbose_name='市')),
                ('distrct', models.CharField(default='光明区', max_length=50, verbose_name='区')),
                ('address', models.CharField(default='公明街道丽水湖畔105号', max_length=50, verbose_name='仓库地址')),
            ],
            options={
                'verbose_name': '仓库信息表',
                'verbose_name_plural': '仓库信息表',
                'db_table': 'item_warehouse_info',
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('item_id', models.CharField(default='1', max_length=2, verbose_name='类别分类代码')),
                ('item', models.CharField(default='采购', max_length=10, verbose_name='类别名称')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_category', to='item.itemcategory', verbose_name='父类别')),
            ],
            options={
                'verbose_name': '物料类别',
                'verbose_name_plural': '物料类别',
                'db_table': 'item_category',
            },
        ),
        migrations.CreateModel(
            name='ItemSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('goods', models.CharField(max_length=64, verbose_name='物料型号:JF-D-002')),
                ('item_id', models.CharField(max_length=20, verbose_name='物料编码:F2.2.09.30.00000')),
                ('name', models.CharField(max_length=20, verbose_name='物料名称')),
                ('desc', models.CharField(max_length=256, verbose_name='物料简介')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='物料价格')),
                ('min_num', models.CharField(max_length=256, verbose_name='最小包装数量')),
                ('current_cnt', models.CharField(max_length=256, verbose_name='库存数量')),
                ('lock_cnt', models.CharField(max_length=50, verbose_name='锁库数量')),
                ('in_transit_cnt', models.CharField(max_length=50, verbose_name='在途数量')),
                ('sales', models.CharField(max_length=50, verbose_name='物料销量')),
                ('spec_0', models.CharField(blank=True, max_length=64, null=True, verbose_name='自定义规格0')),
                ('spec_1', models.CharField(blank=True, max_length=64, null=True, verbose_name='自定义规格1')),
                ('spec_2', models.CharField(blank=True, max_length=64, null=True, verbose_name='自定义规格2')),
                ('spec_3', models.CharField(blank=True, max_length=64, null=True, verbose_name='自定义规格3')),
                ('spec_4', models.CharField(blank=True, max_length=64, null=True, verbose_name='自定义规格4')),
                ('spec_5', models.CharField(blank=True, max_length=64, null=True, verbose_name='自定义规格5')),
                ('spec_6', models.CharField(blank=True, max_length=64, null=True, verbose_name='自定义规格6')),
                ('spec_7', models.CharField(blank=True, max_length=64, null=True, verbose_name='自定义规格7')),
                ('spec_8', models.CharField(blank=True, max_length=64, null=True, verbose_name='自定义规格8')),
                ('spec_9', models.CharField(blank=True, max_length=64, null=True, verbose_name='自定义规格9')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itemsku_itemspecification', to='item.itemspecification', verbose_name='属性类目')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itemsku_itemsupplier', to='item.supplier', verbose_name='供应商名称')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itemsku_itemspecification', to='item.itemunit', verbose_name='物料单位')),
                ('w_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_item', to='item.warehouseinfo', verbose_name='仓库ID')),
            ],
            options={
                'verbose_name': '物料表',
                'verbose_name_plural': '物料表',
                'db_table': 'item_sku',
                'unique_together': {('item_id',)},
            },
        ),
    ]
