# Generated by Django 4.2.6 on 2023-10-18 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsku',
            name='is_launched',
        ),
    ]
