# Generated by Django 4.2.6 on 2023-10-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsku',
            name='min_num',
            field=models.CharField(default=1, max_length=256, verbose_name='最小包装数量'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemspecification',
            name='name_id',
            field=models.CharField(default='1.5.03.01', max_length=9, verbose_name='四级物料代码'),
        ),
    ]
