# Generated by Django 4.2.6 on 2023-10-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='is_activate',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='启用状态'),
        ),
        migrations.AddField(
            model_name='itemsku',
            name='is_activate',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='启用状态'),
        ),
        migrations.AddField(
            model_name='itemspecification',
            name='is_activate',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='启用状态'),
        ),
        migrations.AddField(
            model_name='itemunit',
            name='is_activate',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='启用状态'),
        ),
        migrations.AddField(
            model_name='shippinginfo',
            name='is_activate',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='启用状态'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_activate',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='启用状态'),
        ),
        migrations.AddField(
            model_name='warehouseinfo',
            name='is_activate',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='启用状态'),
        ),
    ]
