# Generated by Django 4.2.6 on 2023-10-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemspecification',
            name='name',
            field=models.CharField(default='PCB属性', max_length=64, verbose_name='物料类属性'),
        ),
        migrations.AlterField(
            model_name='itemspecification',
            name='name_id',
            field=models.CharField(default='1.5.03.01', max_length=64, verbose_name='四级物料代码'),
        ),
    ]
