# Generated by Django 4.2.6 on 2023-10-15 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_warehouseinfo_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseinfo',
            name='is_active',
        ),
    ]
