# Generated by Django 4.2.6 on 2023-10-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_itemsku_min_num_alter_itemspecification_name_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsku',
            name='sales',
            field=models.CharField(max_length=50, verbose_name='物料销量'),
        ),
    ]
