# Generated by Django 4.2.6 on 2023-10-15 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_remove_warehouseinfo_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcategory',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='itemsku',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='itemspecification',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='shippinginfo',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='warehouseinfo',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='warehouseitem',
            name='is_delete',
        ),
    ]
