# Generated by Django 4.2.6 on 2023-10-18 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_itemsku_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsku',
            name='unite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itemsku_itemspecification', to='item.itemunit', verbose_name='物料单位'),
        ),
    ]
