# Generated by Django 4.2.6 on 2023-10-18 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_itemsku_unite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcategory',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='itemsku',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='itemspecification',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='itemunit',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='shippinginfo',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='warehouseinfo',
            name='is_activate',
        ),
    ]
