# Generated by Django 4.2.6 on 2023-10-15 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_remove_itemcategory_is_delete_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouseinfo',
            options={},
        ),
        migrations.AlterModelTable(
            name='warehouseinfo',
            table=None,
        ),
    ]
