# Generated by Django 4.2.6 on 2023-10-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_remove_itemsku_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcategory',
            old_name='is_delete',
            new_name='is_activate',
        ),
        migrations.RemoveField(
            model_name='itemsku',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='itemspecification',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='shippinginfo',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='warehouseinfo',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='warehouseitem',
            name='is_delete',
        ),
        migrations.AddField(
            model_name='itemsku',
            name='is_activate',
            field=models.BooleanField(default=True, verbose_name='启用状态'),
        ),
        migrations.AddField(
            model_name='itemspecification',
            name='is_activate',
            field=models.BooleanField(default=True, verbose_name='启用状态'),
        ),
        migrations.AddField(
            model_name='shippinginfo',
            name='is_activate',
            field=models.BooleanField(default=True, verbose_name='启用状态'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_activate',
            field=models.BooleanField(default=True, verbose_name='启用状态'),
        ),
        migrations.AddField(
            model_name='warehouseinfo',
            name='is_activate',
            field=models.BooleanField(default=True, verbose_name='启用状态'),
        ),
        migrations.AddField(
            model_name='warehouseitem',
            name='is_activate',
            field=models.BooleanField(default=True, verbose_name='启用状态'),
        ),
    ]
