# Generated by Django 4.2.6 on 2023-10-16 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_rename_is_delete_itemcategory_is_activate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcategory',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='itemcategory',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='itemcategory',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='itemsku',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='itemsku',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='itemsku',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='itemspecification',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='itemspecification',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='itemspecification',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='shippinginfo',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='shippinginfo',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='shippinginfo',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='warehouseinfo',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='warehouseinfo',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='warehouseinfo',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='warehouseitem',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='warehouseitem',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='warehouseitem',
            name='update_time',
        ),
    ]
