# Generated by Django 4.2.6 on 2023-10-16 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_remove_itemcategory_create_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemsku',
            options={'verbose_name': '物料表', 'verbose_name_plural': '物料表'},
        ),
        migrations.AlterModelOptions(
            name='itemunit',
            options={'verbose_name': '产品单位表', 'verbose_name_plural': '产品单位表'},
        ),
        migrations.AlterModelOptions(
            name='warehouseinfo',
            options={'verbose_name': '仓库信息表', 'verbose_name_plural': '仓库信息表'},
        ),
        migrations.AlterUniqueTogether(
            name='itemsku',
            unique_together={('item_id',)},
        ),
        migrations.AlterModelTable(
            name='itemsku',
            table='item_item_sku',
        ),
        migrations.AlterModelTable(
            name='itemunit',
            table='item_item_unit',
        ),
        migrations.AlterModelTable(
            name='warehouseinfo',
            table='item_warehouse_info',
        ),
    ]
